chore : EC2 CI/CD 구축

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -14,16 +14,17 @@ jobs:
       - name: Set up JDK
         uses: actions/setup-java@v2
         with:
+          distribution: 'temurin'
           java-version: '17'
 
       - name: Build with Gradle
         run: ./gradlew build -x test
 
       - name: Build Docker image
-        run: docker build --platform linux/amd64 -t ${{ secrets.DOCKERHUB_USERNAME }}/crypto-spring-app:latest .
+        run: docker build --platform linux/amd64 -t rovin1273/crypto-spring-app:latest .
 
       - name: Login to DockerHub
-        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME}}" --password-stdin
+        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "rovin1273" --password-stdin
 
       - name: Push Docker image
         run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/crypto-spring-app:latest
@@ -31,22 +32,29 @@ jobs:
       - name: Execute Docker Container on EC2
         uses: appleboy/ssh-action@master
         with:
-          username: ubuntu
+          username: ${{ secrets.EC2_USERNAME }}
           host: ${{ secrets.EC2_HOST }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           script: |
             docker stop crypto-app || true
             docker rm crypto-app || true
-            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/crypto-spring-app:latest
+            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
+            sleep 5 # DockerHub 로그인 후 대기
+            if ! docker info >/dev/null 2>&1; then
+              echo "Docker login failed"
+              exit 1
+            fi
+            docker pull rovin1273/crypto-spring-app:latest
             docker run -d --name crypto-app -p 8082:8080 --network crypto-network-dev \
-              --env DB_URL=${{ secrets.DB_URL }} \
-              --env DB_USERNAME=${{ secrets.DB_USERNAME }} \
-              --env DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
-              --env REDIS_HOST=${{ secrets.REDIS_HOST }} \
+              --env DB_URL="${{ secrets.DB_URL }}" \
+              --env DB_USERNAME="${{ secrets.DB_USERNAME }}" \
+              --env DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
+              --env REDIS_HOST="${{ secrets.REDIS_HOST }}" \
               --env REDIS_PORT=${{ secrets.REDIS_PORT }} \
-              --env MAIL_USERNAME=${{ secrets.MAIL_USERNAME }} \
-              --env MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }} \
-              --env JWT_SECRET=${{ secrets.JWT_SECRET }} \
-              -v ${{ secrets.STORAGE_UPLOAD_DIR }} \
-              -v ${{ secrets.LOG_DIR }} \
-              ${{ secrets.DOCKERHUB_USERNAME }}/crypto-spring-app:latest
+              --env MAIL_USERNAME="${{ secrets.MAIL_USERNAME }}" \
+              --env MAIL_PASSWORD="${{ secrets.MAIL_PASSWORD }}" \
+              --env JWT_SECRET="${{ secrets.JWT_SECRET }}" \
+              -v /home/ubuntu/volumes/storage/upload:/app/crypto/storage/upload \
+              -v /home/ubuntu/volumes/log:/app/crypto/log \
+              rovin1273/crypto-spring-app:latest
+            docker ps
